force-app/main/default/objects/Engineering_Machine__c/Engineering_Machine__c.object-meta.xml
<CustomObject>
    <label>Engineering Machine</label>
    <nameField>
        <displayFormat>Machine-{0000}</displayFormat>
        <label>Engineering Machine Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Engineering_Machines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Engineering_Machine__c/fields/available_status__c.field-meta.xml
<CustomField>
    <fullName>available_status__c</fullName>
    <label>available status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>available</fullName>
            </value>
            <value>
                <fullName>using in project</fullName>
            </value>
            <value>
                <fullName>in repair</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Engineering_Machine__c/fields/Machine_Name__c.field-meta.xml
<CustomField>
    <fullName>Machine_Name__c</fullName>
    <label>Machine Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Engineering_Machine__c/fields/model__c.field-meta.xml
<CustomField>
    <fullName>model__c</fullName>
    <label>model</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/EMControllerTest.cls
@isTest
public class EMControllerTest {
    @isTest
    static void rungetEMTest(){
        EMController controller=new EMController();
        Engineering_Machine__c em1=new Engineering_Machine__c(Machine_Name__c='test machine1', model__c='Bmodel',available_status__c='using in project');
        insert em1;
        Engineering_Machine__c em2=new Engineering_Machine__c(Machine_Name__c='test machine2', model__c='Amodel',available_status__c='in repair');
        insert em2;
         Engineering_Machine__c em3=new Engineering_Machine__c(Machine_Name__c='test machine3', model__c='Cmodel',available_status__c='available');
        insert em3;
        list<Engineering_Machine__c> em_list=controller.getEMs();
        System.assertEquals(3, em_list.size());
        controller.sortByModel();
        em_list=controller.getEMs();
        System.assertEquals('Amodel', em_list[0].model__c);
        controller.sortByStatus();
        em_list=controller.getEMs();
        System.assertEquals('available', em_list[0].available_status__c);
    }

}