force-app/main/default/objects/Engineering_Machine__c/Engineering_Machine__c.object-meta.xml
<CustomObject>
    <label>Engineering Machine</label>
    <nameField>
        <displayFormat>Machine-{0000}</displayFormat>
        <label>Engineering Machine Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Engineering_Machines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Engineering_Machine__c/fields/Machine_Name__c.field-meta.xml
<CustomField>
    <fullName>Machine_Name__c</fullName>
    <label>Machine Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Engineering_Machine__c/fields/Mining_Project_Id__c.field-meta.xml
<CustomField>
    <fullName>Mining_Project_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Mining Project Id</label>
    <referenceTo>Mining_Project_Id__c</referenceTo>
    <relationshipLabel>Engineering_Machines</relationshipLabel>
    <relationshipName>Engineering_Machines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Mining_Project_Id__c/Mining_Project_Id__c.object-meta.xml
<CustomObject>
    <label>Mining Project Id</label>
    <nameField>
        <displayFormat>MPI-{0000}</displayFormat>
        <label>Mining Project Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mining Project Ids</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Mining_Project_Id__c/fields/Project_Name__c.field-meta.xml
<CustomField>
    <fullName>Project_Name__c</fullName>
    <label>Project Name</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Mining_Project_Id__c/fields/Site_Manager__c.field-meta.xml
<CustomField>
    <fullName>Site_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site Manager</label>
    <referenceTo>Site_Manager__c</referenceTo>
    <relationshipLabel>Mining Project Ids</relationshipLabel>
    <relationshipName>Mining_Project_Ids</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Operations__c/Operations__c.object-meta.xml
<CustomObject>
    <label>Operations</label>
    <nameField>
        <displayFormat>OO-{000}</displayFormat>
        <label>Operations</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Operations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Operations__c/fields/Engineering_Machine__c.field-meta.xml
<CustomField>
    <fullName>Engineering_Machine__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Engineering Machine</label>
    <referenceTo>Engineering_Machine__c</referenceTo>
    <relationshipLabel>Operations</relationshipLabel>
    <relationshipName>Operations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Operations__c/fields/Mining_Project_Id__c.field-meta.xml
<CustomField>
    <fullName>Mining_Project_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Mining Project Id</label>
    <referenceTo>Mining_Project_Id__c</referenceTo>
    <relationshipLabel>Operations</relationshipLabel>
    <relationshipName>Operations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Operations__c/fields/Operations_Goal__c.field-meta.xml
<CustomField>
    <fullName>Operations_Goal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Operations Goal</label>
    <referenceTo>Operations_Goal__c</referenceTo>
    <relationshipLabel>Operations</relationshipLabel>
    <relationshipName>Operations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Operations__c/fields/Site_Manager__c.field-meta.xml
<CustomField>
    <fullName>Site_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site Manager</label>
    <referenceTo>Site_Manager__c</referenceTo>
    <relationshipLabel>Operations</relationshipLabel>
    <relationshipName>Operations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Operations_Goal__c/Operations_Goal__c.object-meta.xml
<CustomObject>
    <description>Mining project goal</description>
    <label>Operations Goal</label>
    <nameField>
        <displayFormat>OPG-{0000}</displayFormat>
        <label>Operation Goal</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Operations Goals</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Operations_Goal__c/fields/Cost_of_Operation__c.field-meta.xml
<CustomField>
    <fullName>Cost_of_Operation__c</fullName>
    <label>Cost of Operation</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Operations_Goal__c/fields/Extraction_Technique__c.field-meta.xml
<CustomField>
    <fullName>Extraction_Technique__c</fullName>
    <label>Extraction Technique</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Surface</fullName>
            </value>
            <value>
                <fullName>Shaft</fullName>
            </value>
            <value>
                <fullName>Magnetic</fullName>
            </value>
            <value>
                <fullName>Heating</fullName>
            </value>
            <value>
                <fullName>Mond</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Operations_Goal__c/fields/Number_of_Digging_Sites__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Digging_Sites__c</fullName>
    <label>Number of Digging Sites</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Operations_Goal__c/fields/Operation_Location__c.field-meta.xml
<CustomField>
    <fullName>Operation_Location__c</fullName>
    <label>Operation Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Earth</fullName>
            </value>
            <value>
                <fullName>Moon</fullName>
            </value>
            <value>
                <fullName>Mars</fullName>
            </value>
            <value>
                <fullName>Titan</fullName>
            </value>
            <value>
                <fullName>Io</fullName>
            </value>
            <value>
                <fullName>Europa</fullName>
            </value>
            <value>
                <fullName>Enceledus</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Operations_Goal__c/fields/Operations__c.field-meta.xml
<CustomField>
    <fullName>Operations__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Operations</label>
    <referenceTo>Operations__c</referenceTo>
    <relationshipLabel>Operations Goals</relationshipLabel>
    <relationshipName>Operations_Goals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Operations_Goal__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Done</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project_Name__c/Project_Name__c.object-meta.xml
<CustomObject>
    <label>Project Name</label>
    <nameField>
        <label>Project Names Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Names</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Site_Manager__c/Site_Manager__c.object-meta.xml
<CustomObject>
    <label>Site Manager</label>
    <nameField>
        <displayFormat>MG-{000}</displayFormat>
        <label>Site Manager Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Managers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Site_Manager__c/fields/Full_Name__c.field-meta.xml
<CustomField>
    <fullName>Full_Name__c</fullName>
    <formula>First_Name__c  &amp; &quot; &quot; &amp;   Last_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Full Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/OperationsControllerTest.cls
@isTest
public class OperationsControllerTest {
    /*
    @AuraEnabled
    public static List<Operations__c> retrieveOperations() {
    List<Operations__c> oList = [SELECT Name, Mining_Project_Id__r.Project_Name__c
    FROM Operations__c];
    Security.stripInaccessible(System.AccessType.READABLE, oList);
    return oList;
    }
    */
    @isTest
    public static void retrieveOperationsTest() {
        
    }
    /*
    @AuraEnabled
    public static List<Operations__c> retrieveOperationInfo(String opName) {
    List<Operations__c> oList = [SELECT Name, Mining_Project_Id__r.Name,
    Site_Manager__r.Full_Name__c,
    Engineering_Machine__r.Machine_Name__c
    FROM Operations__c WHERE Name = :opName];
    Security.stripInaccessible(System.AccessType.READABLE, oList);
    return oList;
    }
    */
    @isTest
    public static void retrieveOperationInfoTest() {
        
    }
    /*
    @AuraEnabled
    public static List<Operations_Goal__c> retrieveOperationGoals(String opName) {
    List<Operations_Goal__c> ogList = [SELECT Name, Operation_Location__c, Operations__r.Name FROM Operations_Goal__c WHERE Operations__r.Name = :opName];
    Security.stripInaccessible(System.AccessType.READABLE, ogList);
    return ogList;
    }
    */
    @isTest
    public static void retrieveOperationGoalsTest() {
        
    }
    /*
    @AuraEnabled
    public static List<Operations_Goal__c> retrieveOpGoalInfo(String ogName) {
    List<Operations_Goal__c> ogList = [SELECT Name, Operation_Location__c,
    Number_of_Digging_Sites__c, Extraction_Technique__c,
    Cost_of_Operation__c, Stage__c
    FROM Operations_Goal__c WHERE Name = :ogName];
    Security.stripInaccessible(System.AccessType.READABLE, ogList);
    return ogList;
    }
    */
    @isTest
    public static void retrieveOpGoalInfoTest() {
        
    }
    /*
    @AuraEnabled
    public static void deleteOpGoal(String opGoalId) {
    Id ogId = opGoalId;
    Operations_Goal__c opGoal = [SELECT Id FROM Operations_Goal__c WHERE Id = :ogId];
    delete opGoal;
    }
    */
    @isTest
    public static void deleteOpGoalTest() {
        
    }
}