force-app/main/default/objects/Engineering_Machine__c/Engineering_Machine__c.object-meta.xml
<CustomObject>
    <label>Engineering Machine</label>
    <nameField>
        <displayFormat>Machine-{0000}</displayFormat>
        <label>Engineering Machine Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Engineering_Machines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Engineering_Machine__c/fields/available_status__c.field-meta.xml
<CustomField>
    <fullName>available_status__c</fullName>
    <label>available status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>available</fullName>
            </value>
            <value>
                <fullName>using in project</fullName>
            </value>
            <value>
                <fullName>in repair</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Engineering_Machine__c/fields/Machine_Name__c.field-meta.xml
<CustomField>
    <fullName>Machine_Name__c</fullName>
    <label>Machine Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Engineering_Machine__c/fields/Mining_Project_Id__c.field-meta.xml
<CustomField>
    <fullName>Mining_Project_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Mining Project Id</label>
    <referenceTo>Mining_Project_Id__c</referenceTo>
    <relationshipLabel>Engineering_Machines</relationshipLabel>
    <relationshipName>Engineering_Machines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engineering_Machine__c/fields/model__c.field-meta.xml
<CustomField>
    <fullName>model__c</fullName>
    <label>model</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Mining_Project_Id__c/Mining_Project_Id__c.object-meta.xml
<CustomObject>
    <label>Mining Project Id</label>
    <nameField>
        <displayFormat>MPI-{0000}</displayFormat>
        <label>Mining Project Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mining Project Ids</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/EMEntryPageController.cls
public with sharing class EMEntryPageController {
    public Engineering_Machine__c EMObj{get;set;}
    String EMId{get;set;}
    public String message{get;set;}
    /**
      fetch current engineering machine
    **/
    public EMEntryPageController () { 
        message = '';
        // Fetching the Current engineering machine Id
        EMId = System.currentPageReference().getParameters().get('Id');
        if(EMId != NULL){
            EMObj = [SELECT  Id, Name, Machine_Name__c, available_status__c, model__c, Mining_Project_Id__c FROM Engineering_Machine__c WHERE id=:EMId];
        }
    }
    /**
      method for saving engineering machine record
    **/
     public PageReference savingEMRecord(){
      try{
         upsert EMObj;
      
         PageReference nextpage= new PageReference('/apex/engineeringmachine');
           return nextpage;
      }
      catch(Exception e){
            message='DataBase has error during saving...';
            ApexPages.addMessage( new ApexPages.Message(ApexPages.Severity.ERROR, message));
            return null;
        }
   }
     public PageReference CancelEMRecord(){
      try{   
         PageReference nextpage= new PageReference('/apex/engineeringmachine');
           return nextpage;
      }
      catch(Exception e){
            message='DataBase has error during saving...';
            ApexPages.addMessage( new ApexPages.Message(ApexPages.Severity.ERROR, message));
            return null;
        }
   }
    
}