force-app/main/default/objects/Machine_and_Tools__c/Machine_and_Tools__c.object-meta.xml
<CustomObject>
    <description>How many Machines will you need for this project?</description>
    <label>Machine and Tools</label>
    <nameField>
        <displayFormat>M-{0000}</displayFormat>
        <label>Machine and Tools</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Machine and Tools</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Mining_Project_Id__c/Mining_Project_Id__c.object-meta.xml
<CustomObject>
    <label>Mining Project Id</label>
    <nameField>
        <displayFormat>MPI-{0000}</displayFormat>
        <label>Mining Project Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mining Project Ids</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Mining_Project_Id__c/fields/Machine_and_Tools__c.field-meta.xml
<CustomField>
    <fullName>Machine_and_Tools__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Machine and Tools</label>
    <referenceTo>Machine_and_Tools__c</referenceTo>
    <relationshipLabel>Mining Project Ids</relationshipLabel>
    <relationshipName>Mining_Project_Ids</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Mining_Project_Id__c/fields/Manager_Name__c.field-meta.xml
<CustomField>
    <fullName>Manager_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Manager Name</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Mining_Project_Ids</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Mining_Project_Id__c/fields/Project_Name__c.field-meta.xml
<CustomField>
    <fullName>Project_Name__c</fullName>
    <label>Project Name</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Operations__c/Operations__c.object-meta.xml
<CustomObject>
    <label>Operations</label>
    <nameField>
        <displayFormat>OO-{000}</displayFormat>
        <label>Operations</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Operations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Operations__c/fields/Machine_and_Tools__c.field-meta.xml
<CustomField>
    <fullName>Machine_and_Tools__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Machine and Tools</label>
    <referenceTo>Machine_and_Tools__c</referenceTo>
    <relationshipLabel>Operations</relationshipLabel>
    <relationshipName>Operations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Operations__c/fields/Manager_Name__c.field-meta.xml
<CustomField>
    <fullName>Manager_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Manager Name</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Operations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Operations__c/fields/Mining_Project_Id__c.field-meta.xml
<CustomField>
    <fullName>Mining_Project_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Mining Project Id</label>
    <referenceTo>Mining_Project_Id__c</referenceTo>
    <relationshipLabel>Operations</relationshipLabel>
    <relationshipName>Operations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Operations__c/fields/Operations_Goal__c.field-meta.xml
<CustomField>
    <fullName>Operations_Goal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Operations Goal</label>
    <referenceTo>Operations_Goal__c</referenceTo>
    <relationshipLabel>Operations</relationshipLabel>
    <relationshipName>Operations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Operations_Goal__c/Operations_Goal__c.object-meta.xml
<CustomObject>
    <description>Mining project goal</description>
    <label>Operations Goal</label>
    <nameField>
        <displayFormat>OPG-{0000}</displayFormat>
        <label>Operation Goal</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Operations Goals</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Operations_Goal__c/fields/Cost_of_Operation__c.field-meta.xml
<CustomField>
    <fullName>Cost_of_Operation__c</fullName>
    <label>Cost of Operation</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Operations_Goal__c/fields/Extraction_Techique__c.field-meta.xml
<CustomField>
    <fullName>Extraction_Techique__c</fullName>
    <label>Extraction Techique</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Surface</fullName>
            </value>
            <value>
                <fullName>Shaft</fullName>
            </value>
            <value>
                <fullName>Magnetic</fullName>
            </value>
            <value>
                <fullName>Heating</fullName>
            </value>
            <value>
                <fullName>Mond</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Operations_Goal__c/fields/Number_of_Digging_Sites__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Digging_Sites__c</fullName>
    <label>Number of Digging Sites</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Operations_Goal__c/fields/Operation_Location__c.field-meta.xml
<CustomField>
    <fullName>Operation_Location__c</fullName>
    <label>Operation Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Earth</fullName>
            </value>
            <value>
                <fullName>Moon</fullName>
            </value>
            <value>
                <fullName>Mars</fullName>
            </value>
            <value>
                <fullName>Titan</fullName>
            </value>
            <value>
                <fullName>Io</fullName>
            </value>
            <value>
                <fullName>Europa</fullName>
            </value>
            <value>
                <fullName>Enceledus</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Operations_Goal__c/fields/Operations__c.field-meta.xml
<CustomField>
    <fullName>Operations__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Operations</label>
    <referenceTo>Operations__c</referenceTo>
    <relationshipLabel>Operations Goals</relationshipLabel>
    <relationshipName>Operations_Goals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Operations_Goal__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Done</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project_Name__c/Project_Name__c.object-meta.xml
<CustomObject>
    <label>Project Name</label>
    <nameField>
        <label>Project Names Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Names</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/Operations_CC.cls
public class Operations_CC {
    public Id operationId {get; set;}
    public Id goalId {get; set;}
    public Operations_Goal__c goal {get; set;}
    public Boolean editMode {get; set;}
    public Operations_Goal__c newGoal {get; set;}

    public Operations_CC() {
        editMode = false;
    }
    public void toggleEditMode() {
        if (newGoal == null || newGoal.Id != null) {
            newGoal = new Operations_Goal__c();
        }
        editMode = !editMode;
    }

    public List<Operations__c> operationList {
        get {
            if (operationList == null) {
                operationList = new List<Operations__c>();
                for (Operations__c operation : [SELECT Name, Mining_Project_Id__r.Project_Name__c FROM Operations__c]) {
                    operationList.add(operation);
                }
            }
            return operationList;
        }
        set;
    }

    public Operations__c operation {
        get {
            if (operation == null) {
                operation = new Operations__c();
                operation = [SELECT Name, Manager_Name__c, Mining_Project_Id__c, Machine_and_Tools__c
                FROM Operations__c WHERE Id = :operationId LIMIT 1];
            }
            return operation;
        }
        set;
    }

    public Operations_Goal__c operationGoal {
        get {
            if (operationGoal == null) {
                operationGoal = new Operations_Goal__c();
                String theId = (String)operationId;
                String whereClause = 'WHERE Operations__c = \'' + theId + '\' LIMIT 1';
                List<String> fieldsToSanitize = new List<String>{'Name', 'Cost_of_Operation__c', 'Extraction_Techique__c', 'Number_of_Digging_Sites__c', 'Operation_Location__c' , 'Stage__c'};
                operationGoal = sanitizeQuery(fieldsToSanitize, 'Operations_Goal__c', whereClause)[0];
            }
            return operationGoal;
        }
        set;
    }

    public List<Operations_Goal__c> goalList {
        get {
            // if (goalList == null) {
                goalList = new List<Operations_Goal__c>();
                for(Operations_Goal__c og : [SELECT Name, Operation_Location__c, Number_of_Digging_Sites__c,Extraction_Techique__c,Cost_of_Operation__c,Stage__c
                FROM Operations_Goal__c WHERE Operations__c = :operationId]) {
                    goalList.add(og);
                }
                System.debug(goalList.size());
            // }
            return goalList;
        }
        set;
    }


    public PageReference saveNew() {
        try {
            newGoal.Operations__c = operationId;
            insert(newGoal);
            editMode = false;
            ApexPages.addMessage(new ApexPages.message(ApexPages.severity.CONFIRM,
                                'Successfully created new goal!'));
            goalId = null;
            return null;
        } catch(System.DMLException e) {
            ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,
                                'Uh oh, something went wrong..'));
            return null;
        }
    }

    public PageReference save() {
        try {
            upsert(goal);
            ApexPages.addMessage(new ApexPages.message(ApexPages.severity.CONFIRM,
                                'Successfully edited the goal!'));
        } catch(System.DMLException e) {
            ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR, 
                                'Uh oh, something went wrong..'));
            return null;
        }
        return null;
    }
    public PageReference cancelCreate() {
        editMode = false;
        return null;
    }

    public PageReference displayDetail() {
        goal = [SELECT Name, Operation_Location__c, Number_of_Digging_Sites__c,Extraction_Techique__c,Cost_of_Operation__c,Stage__c
        FROM Operations_Goal__c WHERE Id = :goalId LIMIT 1];
        System.debug(goal);
        goalId = goal.Id;
        return null;
    }

    public PageReference deleteGoal() {
        ApexPages.addMessage(new ApexPages.message(ApexPages.severity.CONFIRM,
                            'Successfully deleted the goal!'));
        try {
            Operations_Goal__c og = new Operations_Goal__c(Id = goalId);
            delete og;
            editMode = true;
            goalId = null;
        } catch(Exception e) {
            ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,
                                'Uh oh, something went wrong..'));
            return null;
        }
        return null;
    }

    public PageReference showOperation() {
        PageReference pr = Page.SingleOperationPage;
        System.debug(operationId);
        pr.getParameters().put('operationId', operationId);
        return pr;
        
    }
    
    public static List<Operations_Goal__c> sanitizeQuery(List<String> strList, String sObjectName, String whereClauseStr) {
        String queryString = 'SELECT ';
        List<String> fieldsToCheck = new List<String>();
        for (String str : strList) {
            fieldsToCheck.add(str);
        }
        
        Map<String, List<String>> entitiesToCheck = new Map<String, List<String>>();
        entitiesToCheck.put(sObjectName, fieldsToCheck);
        
        Set<String> accessibleFields = checkAccessibility(entitiesToCheck);
        
        queryString += accessibleFields.toString().substring(1, accessibleFields.toString().length() - 1) + ' FROM ' + sObjectName + ' ' + whereClauseStr;
        return Database.query(queryString);

    }

    public static Set<String> checkAccessibility(Map<String, List<String>> entitiesToCheck) {
        List<String> objectNames = new List<String>();
        for(String objectName : entitiesToCheck.keySet()) {
            objectNames.add(objectName);
        }
        
        List<Schema.DescribeSObjectResult> describedObjects = Schema.describeSObjects(objectNames);
        
        Set<String> accessibleFields = new Set<String>();
        
        for(Schema.DescribeSObjectResult dsor : describedObjects) {
            if(dsor.isAccessible()) {
                for(String field : entitiesToCheck.get(dsor.getName())) {
                    if(dsor.fields.getMap().get(field).getDescribe().isAccessible()) {
                        accessibleFields.add(field);
                    }
                }
            }
        }
        return accessibleFields;
    } 
}