force-app/main/default/objects/Machine_and_Tools__c/Machine_and_Tools__c.object-meta.xml
<CustomObject>
    <description>How many Machines will you need for this project?</description>
    <label>Machine and Tools</label>
    <nameField>
        <displayFormat>M-{0000}</displayFormat>
        <label>Machine and Tools</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Machine and Tools</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Mining_Project_Id__c/Mining_Project_Id__c.object-meta.xml
<CustomObject>
    <label>Mining Project Id</label>
    <nameField>
        <displayFormat>MPI-{0000}</displayFormat>
        <label>Mining Project Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mining Project Ids</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Mining_Project_Id__c/fields/Machine_and_Tools__c.field-meta.xml
<CustomField>
    <fullName>Machine_and_Tools__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Machine and Tools</label>
    <referenceTo>Machine_and_Tools__c</referenceTo>
    <relationshipLabel>Mining Project Ids</relationshipLabel>
    <relationshipName>Mining_Project_Ids</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Mining_Project_Id__c/fields/Mining_Project_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Mining_Project_Start_Date__c</fullName>
    <label>Mining Project Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Mining_Project_Id__c/fields/Site_Manager__c.field-meta.xml
<CustomField>
    <fullName>Site_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site Manager</label>
    <referenceTo>Site_Manager__c</referenceTo>
    <relationshipLabel>Mining Project Ids</relationshipLabel>
    <relationshipName>Mining_Project_Ids</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Site_Manager__c/Site_Manager__c.object-meta.xml
<CustomObject>
    <label>Site Manager</label>
    <nameField>
        <displayFormat>MG-{000}</displayFormat>
        <label>Site Manager Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Managers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Site_Manager__c/fields/Agrees_with_the_dangers_of_the_project__c.field-meta.xml
<CustomField>
    <fullName>Agrees_with_the_dangers_of_the_project__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Agrees with the dangers of the project</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/newTaskHandler_Test.cls
@IsTest//(seeAllData=True)
public class newTaskHandler_Test {
    static testMethod void testmethod1()
    {
        List<Site_Manager__c> lstSiteManagers = new List<Site_Manager__c>();
        Test.startTest();
        Machine_and_Tools__c machineTool = new Machine_and_Tools__c();
        //machineTool.Id = 'a005e000001yC4IAAU';
        insert machineTool;
        
        Site_Manager__c siteManager = new Site_Manager__c();
        //siteManager.id  ='a025e000000yW2jAAE';
        siteManager.First_Name__c = 'Test First Name';
        siteManager.Last_Name__c = 'Test Last Name';
         
        insert siteManager;
        
        siteManager.Agrees_with_the_dangers_of_the_project__c = true;
        lstSiteManagers.add(siteManager);
        
        Mining_Project_Id__c miningProject = new Mining_Project_Id__c();
        miningProject.Machine_and_Tools__c = machineTool.id;
        miningProject.Site_Manager__c = siteManager.id;
        miningProject.Mining_Project_Start_Date__c = Date.newInstance(2021, 05, 11);
        insert miningProject;

        newTaskHandler.handlerJobRiskAcceptance(lstSiteManagers);
         Test.stopTest();
    }        
}