force-app/main/default/objects/Machine_and_Tools__c/Machine_and_Tools__c.object-meta.xml
<CustomObject>
    <description>How many Machines will you need for this project?</description>
    <label>Machine and Tools</label>
    <nameField>
        <displayFormat>M-{0000}</displayFormat>
        <label>Machine and Tools</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Machine and Tools</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Mining_Project_Id__c/Mining_Project_Id__c.object-meta.xml
<CustomObject>
    <label>Mining Project Id</label>
    <nameField>
        <displayFormat>MPI-{0000}</displayFormat>
        <label>Mining Project Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mining Project Ids</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Mining_Project_Id__c/fields/Machine_and_Tools__c.field-meta.xml
<CustomField>
    <fullName>Machine_and_Tools__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Machine and Tools</label>
    <referenceTo>Machine_and_Tools__c</referenceTo>
    <relationshipLabel>Mining Project Ids</relationshipLabel>
    <relationshipName>Mining_Project_Ids</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Mining_Project_Id__c/fields/Site_Manager__c.field-meta.xml
<CustomField>
    <fullName>Site_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site Manager</label>
    <referenceTo>Site_Manager__c</referenceTo>
    <relationshipLabel>Mining Project Ids</relationshipLabel>
    <relationshipName>Mining_Project_Ids</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Site_Manager__c/Site_Manager__c.object-meta.xml
<CustomObject>
    <label>Site Manager</label>
    <nameField>
        <displayFormat>MG-{000}</displayFormat>
        <label>Site Manager Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Managers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Site_Manager__c/fields/Agrees_with_the_dangers_of_the_project__c.field-meta.xml
<CustomField>
    <fullName>Agrees_with_the_dangers_of_the_project__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Agrees with the dangers of the project</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/newTaskHandler.cls
public class newTaskHandler {
    //This Handler meets the SOQL, DML and Control FLow requirements requiremts
    public static void handlerJobRiskAcceptance(List<Site_Manager__c> newList){
        //This initialize machineList to an relationship query 
        List<Machine_and_Tools__c>machineList = [SELECT id FROM Machine_and_Tools__c WHERE Id IN(
            SELECT Machine_and_Tools__c FROM Mining_Project_Id__c WHERE Site_Manager__c IN :newList)];
        //init new task object
        List<Task> tList = new List<Task>();                
        for(Site_Manager__c s: newList){
            if(s.Agrees_with_the_dangers_of_the_project__c == true){
                List<Machine_and_Tools__c> ptList = new List<Machine_and_Tools__c>();
                for(Machine_and_Tools__c maList: machineList){
                    Task newTask = new Task();
                    newTask.OwnerId= UserInfo.getUserId();
                    newTask.Subject = 'Call';
                    newTask.Status = 'Not Started';
                    newTask.WhatId = maList.Id;
                    tList.add(newTask);
                }
            }
        }
        insert tList;
    }
}