force-app/main/default/objects/Operations__c/Operations__c.object-meta.xml
<CustomObject>
    <label>Operations</label>
    <nameField>
        <displayFormat>OO-{000}</displayFormat>
        <label>Operations</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Operations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Operations__c/fields/Operations_Goal__c.field-meta.xml
<CustomField>
    <fullName>Operations_Goal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Operations Goal</label>
    <referenceTo>Operations_Goal__c</referenceTo>
    <relationshipLabel>Operations</relationshipLabel>
    <relationshipName>Operations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Operations_Goal__c/Operations_Goal__c.object-meta.xml
<CustomObject>
    <description>Mining project goal</description>
    <label>Operations Goal</label>
    <nameField>
        <displayFormat>OPG-{0000}</displayFormat>
        <label>Operation Goal</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Operations Goals</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Operations_Goal__c/fields/Operations__c.field-meta.xml
<CustomField>
    <fullName>Operations__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Operations</label>
    <referenceTo>Operations__c</referenceTo>
    <relationshipLabel>Operations Goals</relationshipLabel>
    <relationshipName>Operations_Goals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Operations_CC_Test.cls
@isTest
private class Operations_CC_Test {
    @isTest static void OperationsList_Test() {
        Operations__c newOp = new Operations__c();
        Operations_goal__c newOpGoal = new Operations_goal__c();
        Operations_CC controller = new Operations_CC();
        controller.operationId = newOp.Id;
        // controller.goalId = newOpGoal.Id;
        controller.goal = new Operations_Goal__c();
        controller.editMode = false;
        // controller.newGoal =


        controller.toggleEditMode();
        controller.showOperation();
        PageReference pageRef = Page.saveNew;
        Test.setCurrentPage(pageRef);
        controller.saveNew();
        controller.save();
        controller.displayDetail();
        controller.deleteGoal();
        controller.cancelCreate();
    }
}