force-app/main/default/objects/Freight__c/Freight__c.object-meta.xml
<CustomObject>
    <label>Freight</label>
    <nameField>
        <displayFormat>FRE-{000}</displayFormat>
        <label>Freight Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Freights</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Freight__c/fields/Inbound_Arrived_Date__c.field-meta.xml
<CustomField>
    <fullName>Inbound_Arrived_Date__c</fullName>
    <label>Inbound Arrived Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Freight__c/fields/Inbound_Departure_Date__c.field-meta.xml
<CustomField>
    <fullName>Inbound_Departure_Date__c</fullName>
    <label>Inbound Departure Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Freight__c/fields/Inbound_Travel_Time__c.field-meta.xml
<CustomField>
    <fullName>Inbound_Travel_Time__c</fullName>
    <formula>Inbound_Arrived_Date__c -  Inbound_Departure_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Inbound Travel Time</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Freight__c/fields/Mining_Project_Id__c.field-meta.xml
<CustomField>
    <fullName>Mining_Project_Id__c</fullName>
    <label>Mining Project Id</label>
    <referenceTo>Mining_Project_Id__c</referenceTo>
    <relationshipLabel>Freights</relationshipLabel>
    <relationshipName>Freights</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Freight__c/fields/Outbound_Arrival_Date__c.field-meta.xml
<CustomField>
    <fullName>Outbound_Arrival_Date__c</fullName>
    <label>Outbound Arrival Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Freight__c/fields/Outbound_Departure_Date__c.field-meta.xml
<CustomField>
    <fullName>Outbound_Departure_Date__c</fullName>
    <label>Outbound Departure Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Freight__c/fields/Outboune_Travel_Time__c.field-meta.xml
<CustomField>
    <fullName>Outboune_Travel_Time__c</fullName>
    <formula>Outbound_Arrival_Date__c -  Outbound_Departure_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Outboune Travel Time</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Mining_Project_Id__c/Mining_Project_Id__c.object-meta.xml
<CustomObject>
    <label>Mining Project Id</label>
    <nameField>
        <displayFormat>MPI-{0000}</displayFormat>
        <label>Mining Project Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mining Project Ids</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Mining_Project_Id__c/fields/Freight__c.field-meta.xml
<CustomField>
    <fullName>Freight__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Freight</label>
    <referenceTo>Freight__c</referenceTo>
    <relationshipLabel>Mining Project Ids</relationshipLabel>
    <relationshipName>Mining_Project_Ids</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Mining_Project_Id__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Venus</fullName>
            </value>
            <value>
                <fullName>Moon</fullName>
            </value>
            <value>
                <fullName>Mars</fullName>
            </value>
            <value>
                <fullName>Jupiter</fullName>
            </value>
            <value>
                <fullName>Saturn</fullName>
            </value>
            <value>
                <fullName>Io</fullName>
            </value>
            <value>
                <fullName>Enceladus</fullName>
            </value>
            <value>
                <fullName>Europa</fullName>
            </value>
            <value>
                <fullName>Titan</fullName>
            </value>
            <value>
                <fullName>Ceres</fullName>
            </value>
            <value>
                <fullName>Asteroid Belt</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Mining_Project_Id__c/fields/Mineral_or_Element_for_Extraction__c.field-meta.xml
<CustomField>
    <fullName>Mineral_or_Element_for_Extraction__c</fullName>
    <label>Mineral or Element for Extraction</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Lithium</fullName>
            </value>
            <value>
                <fullName>Hydrogen</fullName>
            </value>
            <value>
                <fullName>Helium-3</fullName>
            </value>
            <value>
                <fullName>Methane</fullName>
            </value>
            <value>
                <fullName>Carbon Dioxide</fullName>
            </value>
            <value>
                <fullName>Nickel</fullName>
            </value>
            <value>
                <fullName>Iron</fullName>
            </value>
            <value>
                <fullName>Magnesium</fullName>
            </value>
            <value>
                <fullName>Gold</fullName>
            </value>
            <value>
                <fullName>Copper</fullName>
            </value>
            <value>
                <fullName>Cobalt</fullName>
            </value>
            <value>
                <fullName>Platinum</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Mining_Project_Id__c/fields/Mining_Project_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Mining_Project_Start_Date__c</fullName>
    <label>Mining Project Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Mining_Project_Id__c/fields/Project_Name__c.field-meta.xml
<CustomField>
    <fullName>Project_Name__c</fullName>
    <label>Project Name</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project_Name__c/Project_Name__c.object-meta.xml
<CustomObject>
    <label>Project Name</label>
    <nameField>
        <label>Project Names Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Names</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/displayFreightList.cls
public class displayFreightList {
    @AuraEnabled
    public static list<Mining_Project_Id__c> displayList() {
        List<Mining_Project_Id__c> freightList =[SELECT Id, Project_Name__c, Location__c, 
                                                 Mineral_or_Element_for_Extraction__c, Mining_Project_Start_Date__c 
                                                 FROM Mining_Project_Id__c];
        return freightList;
    }
    
    @AuraEnabled
    public static list<Freight__c> displayFreightList(List<Id> listOfIds){
        List <Freight__c> tripDetails =[SELECT Id, Name, Outbound_Departure_Date__c, Outbound_Arrival_Date__c, Outboune_Travel_Time__c,
                              Inbound_Departure_Date__c, Inbound_Arrived_Date__c, Inbound_Travel_Time__c,
                              Mining_Project_Id__r.Project_Name__c, Mining_Project_Id__r.Location__c
                              FROM Freight__c WHERE Mining_Project_Id__c IN :listOfIds];
        return tripDetails;
    }
}