force-app/main/default/objects/Freight__c/Freight__c.object-meta.xml
<CustomObject>
    <label>Freight</label>
    <nameField>
        <displayFormat>FRE-{000}</displayFormat>
        <label>Freight Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Freights</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Freight__c/fields/Mining_Project_Id__c.field-meta.xml
<CustomField>
    <fullName>Mining_Project_Id__c</fullName>
    <label>Mining Project Id</label>
    <referenceTo>Mining_Project_Id__c</referenceTo>
    <relationshipLabel>Freights</relationshipLabel>
    <relationshipName>Freights</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Mining_Project_Id__c/Mining_Project_Id__c.object-meta.xml
<CustomObject>
    <label>Mining Project Id</label>
    <nameField>
        <displayFormat>MPI-{0000}</displayFormat>
        <label>Mining Project Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mining Project Ids</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Mining_Project_Id__c/fields/Freight__c.field-meta.xml
<CustomField>
    <fullName>Freight__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Freight</label>
    <referenceTo>Freight__c</referenceTo>
    <relationshipLabel>Mining Project Ids</relationshipLabel>
    <relationshipName>Mining_Project_Ids</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Mining_Project_Id__c/fields/Project_Name__c.field-meta.xml
<CustomField>
    <fullName>Project_Name__c</fullName>
    <label>Project Name</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project_Name__c/Project_Name__c.object-meta.xml
<CustomObject>
    <label>Project Name</label>
    <nameField>
        <label>Project Names Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Names</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/freightApexTest.cls
@isTest
private class freightApexTest {
    
    @isTest 
    private static void testDisplayFreightListMiningPositve(){
        List<Mining_Project_Id__c> lstTesting = new List<Mining_Project_Id__c>();
		Mining_Project_Id__c m;
        for(Integer i=0;i<=20;i++){
            m = new Mining_Project_Id__c(Project_Name__c='Testing'+string.valueof(i));
            lstTesting.add(m);
        }
        insert lstTesting;
        List<Mining_Project_Id__c> listOfMiningProjects = displayFreightList.displayList();
        System.assert( listOfMiningProjects != null); 

    }
    
    @isTest
    private static void testDisplayFreightListMiningNegative(){
        List<Mining_Project_Id__c> listOfMiningProjects = displayFreightList.displayList();
        System.assert( listOfMiningProjects.isEmpty(), true); 
    }
    
    @isTest
    private static void testDisplayFreightListFreightPositve(){
        List<Mining_Project_Id__c> lstMiningRef = new List<Mining_Project_Id__c>();
        Mining_Project_Id__c m;
        for(Integer i=0;i<=20;i++){
            m = new Mining_Project_Id__c(Project_Name__c='Testing'+string.valueof(i));
            lstMiningRef.add(m);
        }
        insert lstMiningRef;
        List<Id> refId = new List<Id>();
        for(Mining_Project_Id__c mTest : lstMiningRef ){
            refId.add(mTest.Id);
        }
        List<Freight__c> lstTesting = new List<Freight__c>();
        Freight__c f;
        for(Integer i=0;i<=20;i++){
            for(Integer j=0; j<lstMiningRef.size(); j++){
            f = new Freight__c(Mining_Project_Id__c= lstMiningRef[j].Id);
            lstTesting.add(f);
            }
        }
        insert lstTesting;
        List<Freight__c> listOfFreightTrip = displayFreightList.displayFreightList(refId);
        System.assert( listOfFreightTrip.isEmpty() != null);
        
        
    }
    
    @isTest
    private static void testDisplayFreightListFreightNegative(){
        List<Mining_Project_Id__c> lstMiningRef = new List<Mining_Project_Id__c>();
        insert lstMiningRef;
        List<Id> refId = new List<Id>();
        for(Mining_Project_Id__c m : lstMiningRef ){
            refId.add(m.Id);
        }
        List<Freight__c> listOfFreightTrips = displayFreightList.displayFreightList(refId);
        System.assert( listOfFreightTrips.isEmpty(), true);
    }
    
    @isTest 
    static void testFreightDetailListPositive(){
        List<Mining_Project_Id__c> lstMiningRef = new List<Mining_Project_Id__c>();
        Mining_Project_Id__c m;
        for(Integer i=0;i<=20;i++){
            m = new Mining_Project_Id__c(Project_Name__c='Testing'+string.valueof(i));
            lstMiningRef.add(m);
        }
        insert lstMiningRef;
        List<Freight__c> lstTesting = new List<Freight__c>();
        Freight__c f;
        for(Integer i=0;i<=20;i++){
            for(Integer j=0; j<lstMiningRef.size(); j++){
            f = new Freight__c(Mining_Project_Id__c= lstMiningRef[j].Id);
            lstTesting.add(f);
            }
        }
        insert lstTesting;
        List<Freight__c> listOfFreightDetail = freightDetailList.displayList();
        System.assert( listOfFreightDetail != null);
    }

    @isTest static void testFreightDetailListNegative(){
        List<Freight__c> listOfFreightDetail = freightDetailList.displayList();
        System.assert( listOfFreightDetail.isEmpty(), true);
    }

}