force-app/main/default/objects/Mining_Project_Id__c/Mining_Project_Id__c.object-meta.xml
<CustomObject>
    <label>Mining Project Id</label>
    <nameField>
        <displayFormat>MPI-{0000}</displayFormat>
        <label>Mining Project Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mining Project Ids</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Mining_Project_Id__c/fields/Mineral_or_Element_for_Extraction__c.field-meta.xml
<CustomField>
    <fullName>Mineral_or_Element_for_Extraction__c</fullName>
    <label>Mineral or Element for Extraction</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Lithium</fullName>
            </value>
            <value>
                <fullName>Hydrogen</fullName>
            </value>
            <value>
                <fullName>Helium-3</fullName>
            </value>
            <value>
                <fullName>Methane</fullName>
            </value>
            <value>
                <fullName>Carbon Dioxide</fullName>
            </value>
            <value>
                <fullName>Nickel</fullName>
            </value>
            <value>
                <fullName>Iron</fullName>
            </value>
            <value>
                <fullName>Magnesium</fullName>
            </value>
            <value>
                <fullName>Gold</fullName>
            </value>
            <value>
                <fullName>Copper</fullName>
            </value>
            <value>
                <fullName>Cobalt</fullName>
            </value>
            <value>
                <fullName>Platinum</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Mining_Project_Id__c/fields/Mining_Project_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Mining_Project_Start_Date__c</fullName>
    <label>Mining Project Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Mining_Project_Id__c/fields/Project_Name__c.field-meta.xml
<CustomField>
    <fullName>Project_Name__c</fullName>
    <label>Project Name</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project_Name__c/Project_Name__c.object-meta.xml
<CustomObject>
    <label>Project Name</label>
    <nameField>
        <label>Project Names Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Names</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/Update_Project_Mining_Subject_Test.cls
@IsTest//(seeAllData=True)
public class Update_Project_Mining_Subject_Test {    
    
    static testmethod void testmethod1()
    {
        List<Mining_Project_Id__c> lstMiningProj = new List<Mining_Project_Id__c>();
               
        Mining_Project_Id__c minProj = new Mining_Project_Id__c();
        
        minProj.Mineral_or_Element_for_Extraction__c = 'Lithium';
        minProj.Project_Name__c = 'L: New ProjectName';
        minProj.Mining_Project_Start_Date__c = Date.today();
        lstMiningProj.add(minProj);
        
       // minProj = new Mining_Project_Id__c();
       // minProj.Mineral_or_Element_for_Extraction__c = 'Hydrogen';
       // minProj.Project_Name__c = ':H Not correct Name';
      //  minProj.Mining_Project_Start_Date__c = Date.today();
      //  lstMiningProj.add(minProj);
        
        //Update_Project_Mining_Subject.UpdateProjectMiningSubject(lstMiningProj);
        insert lstMiningProj;
        
        Test.startTest();      
        //
        lstMiningProj[0].Project_Name__c = 'L: newName';
        System.debug(lstMiningProj[0]);
        update lstMiningProj;
        //id testId = lstMiningProj[0];        
        Test.stopTest();
        //List<String> testString = [SELECT Project_Name__c from Mining_Project_Id__c WHERE Project_Name__c = 'newName'];
        
        //System.assertEquals('newName', testString[0]);
    }

}