force-app/main/default/objects/Mining_Project_Id__c/Mining_Project_Id__c.object-meta.xml
<CustomObject>
    <label>Mining Project Id</label>
    <nameField>
        <displayFormat>MPI-{0000}</displayFormat>
        <label>Mining Project Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mining Project Ids</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Mining_Project_Id__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Venus</fullName>
            </value>
            <value>
                <fullName>Moon</fullName>
            </value>
            <value>
                <fullName>Mars</fullName>
            </value>
            <value>
                <fullName>Jupiter</fullName>
            </value>
            <value>
                <fullName>Saturn</fullName>
            </value>
            <value>
                <fullName>Io</fullName>
            </value>
            <value>
                <fullName>Enceladus</fullName>
            </value>
            <value>
                <fullName>Europa</fullName>
            </value>
            <value>
                <fullName>Titan</fullName>
            </value>
            <value>
                <fullName>Ceres</fullName>
            </value>
            <value>
                <fullName>Asteroid Belt</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/planetaryGuideApexController.cls
public with sharing class planetaryGuideApexController {
    
    @AuraEnabled
    public static Integer fetchLocationTotal()
    {
        List<Mining_Project_Id__c> results = [SELECT Location__c FROM Mining_Project_Id__c WHERE Location__c != Null];
        
        
        return results.size();
    }
    
    @AuraEnabled
    public static List<Integer> fetchMiningProjects() {
        List<Mining_Project_Id__c> results = [SELECT Location__c FROM Mining_Project_Id__c WHERE Location__c != Null ORDER BY Location__C DESC];
        List<Integer> returnList = new List<Integer>();
        Set<String> fieldBreakDown = new Set<String>();
        
        
        
        for(Mining_Project_Id__c result : results)
        {
            fieldBreakDown.add(result.Location__c);
        }
        
        for(String str : fieldBreakDown){
            System.debug('Currently against ' + str);
            Integer counter = 0;
            for(Mining_Project_Id__c result : results)
            {
                if(result.Location__c == str)
                {
                    counter++;
                }
            }
            returnList.add(counter);
        }
        
        return returnList;
    }
    
}