force-app/main/default/objects/Mining_Project_Id__c/Mining_Project_Id__c.object-meta.xml
<CustomObject>
    <label>Mining Project Id</label>
    <nameField>
        <displayFormat>MPI-{0000}</displayFormat>
        <label>Mining Project Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mining Project Ids</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Mining_Project_Id__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Venus</fullName>
            </value>
            <value>
                <fullName>Moon</fullName>
            </value>
            <value>
                <fullName>Mars</fullName>
            </value>
            <value>
                <fullName>Jupiter</fullName>
            </value>
            <value>
                <fullName>Saturn</fullName>
            </value>
            <value>
                <fullName>Io</fullName>
            </value>
            <value>
                <fullName>Enceladus</fullName>
            </value>
            <value>
                <fullName>Europa</fullName>
            </value>
            <value>
                <fullName>Titan</fullName>
            </value>
            <value>
                <fullName>Ceres</fullName>
            </value>
            <value>
                <fullName>Asteroid Belt</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Mining_Project_Id__c/fields/Mineral_or_Element_for_Extraction__c.field-meta.xml
<CustomField>
    <fullName>Mineral_or_Element_for_Extraction__c</fullName>
    <label>Mineral or Element for Extraction</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Lithium</fullName>
            </value>
            <value>
                <fullName>Hydrogen</fullName>
            </value>
            <value>
                <fullName>Helium-3</fullName>
            </value>
            <value>
                <fullName>Methane</fullName>
            </value>
            <value>
                <fullName>Carbon Dioxide</fullName>
            </value>
            <value>
                <fullName>Nickel</fullName>
            </value>
            <value>
                <fullName>Iron</fullName>
            </value>
            <value>
                <fullName>Magnesium</fullName>
            </value>
            <value>
                <fullName>Gold</fullName>
            </value>
            <value>
                <fullName>Copper</fullName>
            </value>
            <value>
                <fullName>Cobalt</fullName>
            </value>
            <value>
                <fullName>Platinum</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Mining_Project_Id__c/fields/Mining_Project_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Mining_Project_Start_Date__c</fullName>
    <label>Mining Project Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Mining_Project_Id__c/fields/Project_Name__c.field-meta.xml
<CustomField>
    <fullName>Project_Name__c</fullName>
    <label>Project Name</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project_Name__c/Project_Name__c.object-meta.xml
<CustomObject>
    <label>Project Name</label>
    <nameField>
        <label>Project Names Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Names</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/planetaryGuideApexController_Test.cls
@isTest
public class planetaryGuideApexController_Test {
	

	@isTest
    private static void pGAC_MainTest() {
		List<Mining_Project_Id__c> projs = new List<Mining_Project_Id__c>();
       

        Mining_Project_Id__c png = new Mining_Project_Id__c();
        
            png.Project_Name__c = 'Project_Name' + 1 + ' ';
            png.Location__c = 'Moon';
            png.Mineral_or_Element_for_Extraction__c = 'Iron';
            png.Mining_Project_Start_Date__c = Date.today() + 1;
            projs.add(png);
        
        insert projs;
        
        planetaryGuideApexController.fetchLocationTotal();

		planetaryGuideApexController.fetchMiningProjects();
    }
    
}