force-app/main/default/objects/Mining_Project_Id__c/Mining_Project_Id__c.object-meta.xml
<CustomObject>
    <label>Mining Project Id</label>
    <nameField>
        <displayFormat>MPI-{0000}</displayFormat>
        <label>Mining Project Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mining Project Ids</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Mining_Project_Id__c/fields/Hazardous_Issues__c.field-meta.xml
<CustomField>
    <fullName>Hazardous_Issues__c</fullName>
    <label>Hazardous Issues</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Corrosive Environment</fullName>
            </value>
            <value>
                <fullName>High Radiation</fullName>
            </value>
            <value>
                <fullName>Low Gravity</fullName>
            </value>
            <value>
                <fullName>Low Atmosphere Pressure</fullName>
            </value>
            <value>
                <fullName>High Temperatures</fullName>
            </value>
            <value>
                <fullName>Low Temperatures</fullName>
            </value>
            <value>
                <fullName>Crashing Atmosphere Pressure</fullName>
            </value>
            <value>
                <fullName>Volcanic Activity</fullName>
            </value>
            <value>
                <fullName>Crashing Gravity</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Mining_Project_Id__c/fields/Project_Name__c.field-meta.xml
<CustomField>
    <fullName>Project_Name__c</fullName>
    <label>Project Name</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project_Name__c/Project_Name__c.object-meta.xml
<CustomObject>
    <label>Project Name</label>
    <nameField>
        <label>Project Names Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Names</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/RiskLevelPageSCTest.cls
@isTest
private class RiskLevelPageSCTest {
 
    @testSetup
    private static void loadTestData() {
        List<Mining_Project_Id__c> testMining = new List<Mining_Project_Id__c>();
        for(Integer i=0;i<4;i++) {
            testMining.add(new Mining_Project_Id__c(Project_Name__c = 'projectTest' + i, Hazardous_Issues__c = 'Corrosive Environment'));
        }
        insert testMining;    
    }
    
    @isTest
    private static void testGetMiningList() {
        test.startTest();
        List<Mining_Project_Id__c> mining = RiskLevelPageSearchController.getMiningList('projectTest1');
        test.stopTest();
           
    }
    
    @isTest
    private static void testGetMiningListFail() {
        test.startTest();
        List<Mining_Project_Id__c> mining = RiskLevelPageSearchController.getMiningList('projectTest50');
        test.stopTest();
           
    }
}