force-app/main/default/objects/Mining_Project_Id__c/Mining_Project_Id__c.object-meta.xml
<CustomObject>
    <label>Mining Project Id</label>
    <nameField>
        <displayFormat>MPI-{0000}</displayFormat>
        <label>Mining Project Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mining Project Ids</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Mining_Project_Id__c/fields/Mining_Project_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Mining_Project_Start_Date__c</fullName>
    <label>Mining Project Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Mining_Project_Id__c/fields/Project_Name__c.field-meta.xml
<CustomField>
    <fullName>Project_Name__c</fullName>
    <label>Project Name</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project_Name__c/Project_Name__c.object-meta.xml
<CustomObject>
    <label>Project Name</label>
    <nameField>
        <label>Project Names Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Names</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ValidateStartDate_Test.cls
@IsTest//(seeAllData=True)
public class ValidateStartDate_Test {
  static testMethod void testRecordWithDate()
    {
        List<Mining_Project_Id__c> lstProjectIds = new List<Mining_Project_Id__c>();
        Mining_Project_Id__c miningProjct = new Mining_Project_Id__c();
               
        miningProjct.Project_Name__c = 'Test Project';
        miningProjct.Mining_Project_Start_Date__c =  Date.newInstance(2021, 05, 10);
        lstProjectIds.add(miningProjct);
        
        miningProjct = new Mining_Project_Id__c();        
        miningProjct.Project_Name__c = 'Test Project2';
        miningProjct.Mining_Project_Start_Date__c =  Date.newInstance(2021, 04, 20);
        lstProjectIds.add(miningProjct);       
        
        insert lstProjectIds;
        
        Test.startTest(); 
        delete lstProjectIds;
        Test.stopTest();
        
       // ValidateStartHandler.ValidateStart(lstProjectIds);
        
        
        
    } 
}