force-app/main/default/objects/Mining_Project_Id__c/Mining_Project_Id__c.object-meta.xml
<CustomObject>
    <label>Mining Project Id</label>
    <nameField>
        <displayFormat>MPI-{0000}</displayFormat>
        <label>Mining Project Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mining Project Ids</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Mining_Project_Id__c/fields/Hazard_Count__c.field-meta.xml
<CustomField>
    <fullName>Hazard_Count__c</fullName>
    <formula>IF(INCLUDES(Hazardous_Issues__c, &apos;Corrosive Environment&apos;), 1, 0) 
+ IF(INCLUDES(Hazardous_Issues__c, &apos;High Radiation&apos;), 1, 0) 
+ IF(INCLUDES(Hazardous_Issues__c, &apos;Low Gravity&apos;), 1, 0)
+ IF(INCLUDES(Hazardous_Issues__c, &apos;Low Atmosphere Pressure&apos;), 1, 0)
+ IF(INCLUDES(Hazardous_Issues__c, &apos;High Temperatures&apos;), 1, 0)
+ IF(INCLUDES(Hazardous_Issues__c, &apos;Low Temperatures&apos;), 1, 0)
+ IF(INCLUDES(Hazardous_Issues__c, &apos;Crashing Atmosphere Pressure&apos;), 1, 0)
+ IF(INCLUDES(Hazardous_Issues__c, &apos;Volcanic Activity&apos;), 1, 0)
+ IF(INCLUDES(Hazardous_Issues__c, &apos;Crashing Gravity&apos;), 1, 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Hazard Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Mining_Project_Id__c/fields/Hazardous_Issues__c.field-meta.xml
<CustomField>
    <fullName>Hazardous_Issues__c</fullName>
    <label>Hazardous Issues</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Corrosive Environment</fullName>
            </value>
            <value>
                <fullName>High Radiation</fullName>
            </value>
            <value>
                <fullName>Low Gravity</fullName>
            </value>
            <value>
                <fullName>Low Atmosphere Pressure</fullName>
            </value>
            <value>
                <fullName>High Temperatures</fullName>
            </value>
            <value>
                <fullName>Low Temperatures</fullName>
            </value>
            <value>
                <fullName>Crashing Atmosphere Pressure</fullName>
            </value>
            <value>
                <fullName>Volcanic Activity</fullName>
            </value>
            <value>
                <fullName>Crashing Gravity</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Mining_Project_Id__c/fields/Project_Name__c.field-meta.xml
<CustomField>
    <fullName>Project_Name__c</fullName>
    <label>Project Name</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project_Name__c/Project_Name__c.object-meta.xml
<CustomObject>
    <label>Project Name</label>
    <nameField>
        <label>Project Names Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Names</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/RiskLevelSearchController.cls
public  with sharing class RiskLevelSearchController {
    
    // The User's input
    public String projectName { get; set; }

    public List<Mining_Project_Id__c> projectSearchResult { get; set; }

    public void projectQuery() {

        projectName = projectName.trim();

        projectSearchResult = [
            SELECT Name, Project_Name__c, Hazardous_Issues__c, Hazard_Count__c
              FROM Mining_Project_Id__c
             WHERE Project_Name__c = :projectName
             LIMIT 1
        ];
    }

}