force-app/main/default/objects/Site_Manager__c/Site_Manager__c.object-meta.xml
<CustomObject>
    <label>Site Manager</label>
    <nameField>
        <displayFormat>MG-{000}</displayFormat>
        <label>Site Manager Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Managers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Site_Manager__c/fields/Agrees_with_the_dangers_of_the_project__c.field-meta.xml
<CustomField>
    <fullName>Agrees_with_the_dangers_of_the_project__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Agrees with the dangers of the project</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Site_Manager__c/fields/Emergency_Contact__c.field-meta.xml
<CustomField>
    <fullName>Emergency_Contact__c</fullName>
    <label>Emergency Contact</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ManagingManagersControllerTest.cls
@isTest
public class ManagingManagersControllerTest {
    /*
    @AuraEnabled
    public static List<Site_Manager__c> retrieveManagers() {
        List<Site_Manager__c> smList = [SELECT First_Name__c, Last_Name__c, Email__c, 
                                        Emergency_Contact__c, Agrees_with_the_dangers_of_the_project__c 
                                        FROM Site_Manager__c];
        Security.stripInaccessible(System.AccessType.READABLE, smList);
        return smList;
    }
	*/
    
    @isTest
    private static void retrieveManagersTest() {
        
    }
}