force-app/main/default/objects/Space_Travel__c/Space_Travel__c.object-meta.xml
<CustomObject>
    <label>Space Travel</label>
    <nameField>
        <label>Space Travel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Space Travels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Space_Travel__c/fields/Food_Storage__c.field-meta.xml
<CustomField>
    <fullName>Food_Storage__c</fullName>
    <label>Food Storage</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Space_Travel__c/fields/Fuel_Cost__c.field-meta.xml
<CustomField>
    <fullName>Fuel_Cost__c</fullName>
    <label>Fuel Cost</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Space_Travel__c/fields/Planet_Destination__c.field-meta.xml
<CustomField>
    <fullName>Planet_Destination__c</fullName>
    <label>Planet Destination</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mercury</fullName>
            </value>
            <value>
                <fullName>Venus</fullName>
            </value>
            <value>
                <fullName>Mars</fullName>
            </value>
            <value>
                <fullName>Jupiter</fullName>
            </value>
            <value>
                <fullName>Saturn</fullName>
            </value>
            <value>
                <fullName>Uranus</fullName>
            </value>
            <value>
                <fullName>Neptune</fullName>
            </value>
            <value>
                <fullName>Moon</fullName>
            </value>
            <value>
                <fullName>Io</fullName>
            </value>
            <value>
                <fullName>Enceladus</fullName>
            </value>
            <value>
                <fullName>Europa</fullName>
            </value>
            <value>
                <fullName>Titan</fullName>
            </value>
            <value>
                <fullName>Ceres</fullName>
            </value>
            <value>
                <fullName>Asteroid Belt</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Space_Travel__c/fields/Ship__c.field-meta.xml
<CustomField>
    <fullName>Ship__c</fullName>
    <label>Ship</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DisplayListofSpaceTravelsTest.cls
@isTest
private class DisplayListofSpaceTravelsTest {
    @isTest
    private static void spaceTravelTest(){
        List<Space_Travel__c> testRun = new List<Space_Travel__c>();
        for(Integer i=0; i<10; i++){
            Space_Travel__c testTravel = new Space_Travel__c();
            testTravel.Name = 'John Trip ' + i;
            testTravel.Ship__c = 'Ship Bean' + i;
            testTravel.Fuel_Cost__c= 652150;
            testTravel.Food_Storage__c= 10000;
            testTravel.Planet_Destination__c= 'Titan';
            testRun.add(testTravel);
        }    
        DisplayListofSpaceTravels.fetchSpaceRecords();
    }
}